services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    networks:
      - tcc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/nodes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - SERVER_PORT_GRPC=8080
      - SERVER_PORT_HTTP=8081
    ports:
      - 8080:8080

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    networks:
      - tcc-network
    depends_on:
      - server
    restart: unless-stopped
    environment:
      - SERVER_HOSTNAME=server
      - SERVER_PORT_GRPC=8080

  minio:
    image: minio/minio:latest
    networks:
      - tcc-network
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  tcc-network:
    driver: bridge
