// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: internal/grpc/transcoding/transcoding.proto

package transcoding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Unique identifier for request/response correlation
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBase) Reset() {
	*x = MessageBase{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBase) ProtoMessage() {}

func (x *MessageBase) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBase.ProtoReflect.Descriptor instead.
func (*MessageBase) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBase) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageBase) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type EncodingProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Codec         string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	Params        []string               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	EncodeTime    float64                `protobuf:"fixed64,4,opt,name=encode_time,json=encodeTime,proto3" json:"encode_time,omitempty"`
	DecodeTime    float64                `protobuf:"fixed64,5,opt,name=decode_time,json=decodeTime,proto3" json:"decode_time,omitempty"`
	Fps           float64                `protobuf:"fixed64,6,opt,name=fps,proto3" json:"fps,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodingProfile) Reset() {
	*x = EncodingProfile{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodingProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodingProfile) ProtoMessage() {}

func (x *EncodingProfile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodingProfile.ProtoReflect.Descriptor instead.
func (*EncodingProfile) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{1}
}

func (x *EncodingProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EncodingProfile) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *EncodingProfile) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *EncodingProfile) GetEncodeTime() float64 {
	if x != nil {
		return x.EncodeTime
	}
	return 0
}

func (x *EncodingProfile) GetDecodeTime() float64 {
	if x != nil {
		return x.DecodeTime
	}
	return 0
}

func (x *EncodingProfile) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *EncodingProfile) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Messages sent FROM nodes TO orchestrator
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *MessageBase           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_RegisterRequest
	//	*NodeMessage_ResourceUsageRequest
	//	*NodeMessage_DisconnectRequest
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetBase() *MessageBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetResourceUsageRequest() *ResourceUsageRequest {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ResourceUsageRequest); ok {
			return x.ResourceUsageRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetDisconnectRequest() *DisconnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_DisconnectRequest); ok {
			return x.DisconnectRequest
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,2,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type NodeMessage_ResourceUsageRequest struct {
	ResourceUsageRequest *ResourceUsageRequest `protobuf:"bytes,3,opt,name=resource_usage_request,json=resourceUsageRequest,proto3,oneof"`
}

type NodeMessage_DisconnectRequest struct {
	DisconnectRequest *DisconnectRequest `protobuf:"bytes,5,opt,name=disconnect_request,json=disconnectRequest,proto3,oneof"`
}

func (*NodeMessage_RegisterRequest) isNodeMessage_Payload() {}

func (*NodeMessage_ResourceUsageRequest) isNodeMessage_Payload() {}

func (*NodeMessage_DisconnectRequest) isNodeMessage_Payload() {}

// Messages sent FROM orchestrator TO nodes
type OrchestratorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *MessageBase           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OrchestratorMessage_RegisterResponse
	//	*OrchestratorMessage_JobAssignmentRequest
	//	*OrchestratorMessage_DisconnectResponse
	Payload       isOrchestratorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{3}
}

func (x *OrchestratorMessage) GetBase() *MessageBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrchestratorMessage) GetPayload() isOrchestratorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OrchestratorMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetJobAssignmentRequest() *JobAssignmentRequest {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_JobAssignmentRequest); ok {
			return x.JobAssignmentRequest
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetDisconnectResponse() *DisconnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_DisconnectResponse); ok {
			return x.DisconnectResponse
		}
	}
	return nil
}

type isOrchestratorMessage_Payload interface {
	isOrchestratorMessage_Payload()
}

type OrchestratorMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type OrchestratorMessage_JobAssignmentRequest struct {
	JobAssignmentRequest *JobAssignmentRequest `protobuf:"bytes,4,opt,name=job_assignment_request,json=jobAssignmentRequest,proto3,oneof"`
}

type OrchestratorMessage_DisconnectResponse struct {
	DisconnectResponse *DisconnectResponse `protobuf:"bytes,7,opt,name=disconnect_response,json=disconnectResponse,proto3,oneof"`
}

func (*OrchestratorMessage_RegisterResponse) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_JobAssignmentRequest) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_DisconnectResponse) isOrchestratorMessage_Payload() {}

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EncodingProfiles []*EncodingProfile     `protobuf:"bytes,2,rep,name=encoding_profiles,json=encodingProfiles,proto3" json:"encoding_profiles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEncodingProfiles() []*EncodingProfile {
	if x != nil {
		return x.EncodingProfiles
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResourceUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,4,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageRequest) Reset() {
	*x = ResourceUsageRequest{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageRequest) ProtoMessage() {}

func (x *ResourceUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageRequest.ProtoReflect.Descriptor instead.
func (*ResourceUsageRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceUsageRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceUsageRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsageRequest) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ResourceUsageRequest) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

type ResourceUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageResponse) Reset() {
	*x = ResourceUsageResponse{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageResponse) ProtoMessage() {}

func (x *ResourceUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageResponse.ProtoReflect.Descriptor instead.
func (*ResourceUsageResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResourceUsageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	InputPath     string                 `protobuf:"bytes,2,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	Crf           string                 `protobuf:"bytes,4,opt,name=crf,proto3" json:"crf,omitempty"`
	Preset        string                 `protobuf:"bytes,5,opt,name=preset,proto3" json:"preset,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,6,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,7,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignmentRequest) Reset() {
	*x = JobAssignmentRequest{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignmentRequest) ProtoMessage() {}

func (x *JobAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignmentRequest.ProtoReflect.Descriptor instead.
func (*JobAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{8}
}

func (x *JobAssignmentRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignmentRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *JobAssignmentRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *JobAssignmentRequest) GetCrf() string {
	if x != nil {
		return x.Crf
	}
	return ""
}

func (x *JobAssignmentRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *JobAssignmentRequest) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *JobAssignmentRequest) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

type JobAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignmentResponse) Reset() {
	*x = JobAssignmentResponse{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignmentResponse) ProtoMessage() {}

func (x *JobAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignmentResponse.ProtoReflect.Descriptor instead.
func (*JobAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{9}
}

func (x *JobAssignmentResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignmentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JobAssignmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{10}
}

func (x *DisconnectRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{11}
}

func (x *DisconnectResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type GetAllNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNodesRequest) Reset() {
	*x = GetAllNodesRequest{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNodesRequest) ProtoMessage() {}

func (x *GetAllNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNodesRequest.ProtoReflect.Descriptor instead.
func (*GetAllNodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{12}
}

type NodeInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EncodingProfiles []*EncodingProfile     `protobuf:"bytes,3,rep,name=encoding_profiles,json=encodingProfiles,proto3" json:"encoding_profiles,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent    float64                `protobuf:"fixed64,5,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent      float64                `protobuf:"fixed64,6,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	LastSeen         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{13}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetEncodingProfiles() []*EncodingProfile {
	if x != nil {
		return x.EncodingProfiles
	}
	return nil
}

func (x *NodeInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *NodeInfo) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *NodeInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type GetAllNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNodesResponse) Reset() {
	*x = GetAllNodesResponse{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNodesResponse) ProtoMessage() {}

func (x *GetAllNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNodesResponse.ProtoReflect.Descriptor instead.
func (*GetAllNodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetAllNodesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type EnqueueJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputPath     string                 `protobuf:"bytes,1,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,6,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueJobRequest) Reset() {
	*x = EnqueueJobRequest{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueJobRequest) ProtoMessage() {}

func (x *EnqueueJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueJobRequest.ProtoReflect.Descriptor instead.
func (*EnqueueJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{15}
}

func (x *EnqueueJobRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *EnqueueJobRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *EnqueueJobRequest) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

type EnqueueJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueJobResponse) Reset() {
	*x = EnqueueJobResponse{}
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueJobResponse) ProtoMessage() {}

func (x *EnqueueJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_transcoding_transcoding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueJobResponse.ProtoReflect.Descriptor instead.
func (*EnqueueJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP(), []int{16}
}

func (x *EnqueueJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnqueueJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_grpc_transcoding_transcoding_proto protoreflect.FileDescriptor

const file_internal_grpc_transcoding_transcoding_proto_rawDesc = "" +
	"\n" +
	"+internal/grpc/transcoding/transcoding.proto\x12\vtranscoding\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\vMessageBase\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xbd\x01\n" +
	"\x0fEncodingProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x16\n" +
	"\x06params\x18\x03 \x03(\tR\x06params\x12\x1f\n" +
	"\vencode_time\x18\x04 \x01(\x01R\n" +
	"encodeTime\x12\x1f\n" +
	"\vdecode_time\x18\x05 \x01(\x01R\n" +
	"decodeTime\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\x01R\x03fps\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\"\xbd\x02\n" +
	"\vNodeMessage\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.transcoding.MessageBaseR\x04base\x12I\n" +
	"\x10register_request\x18\x02 \x01(\v2\x1c.transcoding.RegisterRequestH\x00R\x0fregisterRequest\x12Y\n" +
	"\x16resource_usage_request\x18\x03 \x01(\v2!.transcoding.ResourceUsageRequestH\x00R\x14resourceUsageRequest\x12O\n" +
	"\x12disconnect_request\x18\x05 \x01(\v2\x1e.transcoding.DisconnectRequestH\x00R\x11disconnectRequestB\t\n" +
	"\apayload\"\xcb\x02\n" +
	"\x13OrchestratorMessage\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.transcoding.MessageBaseR\x04base\x12L\n" +
	"\x11register_response\x18\x02 \x01(\v2\x1d.transcoding.RegisterResponseH\x00R\x10registerResponse\x12Y\n" +
	"\x16job_assignment_request\x18\x04 \x01(\v2!.transcoding.JobAssignmentRequestH\x00R\x14jobAssignmentRequest\x12R\n" +
	"\x13disconnect_response\x18\a \x01(\v2\x1f.transcoding.DisconnectResponseH\x00R\x12disconnectResponseB\t\n" +
	"\apayload\"p\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12I\n" +
	"\x11encoding_profiles\x18\x02 \x03(\v2\x1c.transcoding.EncodingProfileR\x10encodingProfiles\"_\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9a\x01\n" +
	"\x14ResourceUsageRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x04 \x01(\x01R\vdiskPercent\"K\n" +
	"\x15ResourceUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd9\x01\n" +
	"\x14JobAssignmentRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"input_path\x18\x02 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\x12\x10\n" +
	"\x03crf\x18\x04 \x01(\tR\x03crf\x12\x16\n" +
	"\x06preset\x18\x05 \x01(\tR\x06preset\x12\x1f\n" +
	"\vaudio_codec\x18\x06 \x01(\tR\n" +
	"audioCodec\x12\x1f\n" +
	"\vvideo_codec\x18\a \x01(\tR\n" +
	"videoCodec\"d\n" +
	"\x15JobAssignmentResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"D\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x12DisconnectResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x14\n" +
	"\x12GetAllNodesRequest\"\xa6\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\x11encoding_profiles\x18\x03 \x03(\v2\x1c.transcoding.EncodingProfileR\x10encodingProfiles\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x05 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x06 \x01(\x01R\vdiskPercent\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"c\n" +
	"\x13GetAllNodesResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.transcoding.NodeInfoR\x05nodes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"t\n" +
	"\x11EnqueueJobRequest\x12\x1d\n" +
	"\n" +
	"input_path\x18\x01 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x1f\n" +
	"\vvideo_codec\x18\x06 \x01(\tR\n" +
	"videoCodec\"_\n" +
	"\x12EnqueueJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xfd\x01\n" +
	"\x10VideoTranscoding\x12H\n" +
	"\x06Stream\x12\x18.transcoding.NodeMessage\x1a .transcoding.OrchestratorMessage(\x010\x01\x12P\n" +
	"\vGetAllNodes\x12\x1f.transcoding.GetAllNodesRequest\x1a .transcoding.GetAllNodesResponse\x12M\n" +
	"\n" +
	"EnqueueJob\x12\x1e.transcoding.EnqueueJobRequest\x1a\x1f.transcoding.EnqueueJobResponseB4Z2github.com/svaan1/tcc-go/internal/grpc/transcodingb\x06proto3"

var (
	file_internal_grpc_transcoding_transcoding_proto_rawDescOnce sync.Once
	file_internal_grpc_transcoding_transcoding_proto_rawDescData []byte
)

func file_internal_grpc_transcoding_transcoding_proto_rawDescGZIP() []byte {
	file_internal_grpc_transcoding_transcoding_proto_rawDescOnce.Do(func() {
		file_internal_grpc_transcoding_transcoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_transcoding_transcoding_proto_rawDesc), len(file_internal_grpc_transcoding_transcoding_proto_rawDesc)))
	})
	return file_internal_grpc_transcoding_transcoding_proto_rawDescData
}

var file_internal_grpc_transcoding_transcoding_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_grpc_transcoding_transcoding_proto_goTypes = []any{
	(*MessageBase)(nil),           // 0: transcoding.MessageBase
	(*EncodingProfile)(nil),       // 1: transcoding.EncodingProfile
	(*NodeMessage)(nil),           // 2: transcoding.NodeMessage
	(*OrchestratorMessage)(nil),   // 3: transcoding.OrchestratorMessage
	(*RegisterRequest)(nil),       // 4: transcoding.RegisterRequest
	(*RegisterResponse)(nil),      // 5: transcoding.RegisterResponse
	(*ResourceUsageRequest)(nil),  // 6: transcoding.ResourceUsageRequest
	(*ResourceUsageResponse)(nil), // 7: transcoding.ResourceUsageResponse
	(*JobAssignmentRequest)(nil),  // 8: transcoding.JobAssignmentRequest
	(*JobAssignmentResponse)(nil), // 9: transcoding.JobAssignmentResponse
	(*DisconnectRequest)(nil),     // 10: transcoding.DisconnectRequest
	(*DisconnectResponse)(nil),    // 11: transcoding.DisconnectResponse
	(*GetAllNodesRequest)(nil),    // 12: transcoding.GetAllNodesRequest
	(*NodeInfo)(nil),              // 13: transcoding.NodeInfo
	(*GetAllNodesResponse)(nil),   // 14: transcoding.GetAllNodesResponse
	(*EnqueueJobRequest)(nil),     // 15: transcoding.EnqueueJobRequest
	(*EnqueueJobResponse)(nil),    // 16: transcoding.EnqueueJobResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_internal_grpc_transcoding_transcoding_proto_depIdxs = []int32{
	17, // 0: transcoding.MessageBase.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: transcoding.NodeMessage.base:type_name -> transcoding.MessageBase
	4,  // 2: transcoding.NodeMessage.register_request:type_name -> transcoding.RegisterRequest
	6,  // 3: transcoding.NodeMessage.resource_usage_request:type_name -> transcoding.ResourceUsageRequest
	10, // 4: transcoding.NodeMessage.disconnect_request:type_name -> transcoding.DisconnectRequest
	0,  // 5: transcoding.OrchestratorMessage.base:type_name -> transcoding.MessageBase
	5,  // 6: transcoding.OrchestratorMessage.register_response:type_name -> transcoding.RegisterResponse
	8,  // 7: transcoding.OrchestratorMessage.job_assignment_request:type_name -> transcoding.JobAssignmentRequest
	11, // 8: transcoding.OrchestratorMessage.disconnect_response:type_name -> transcoding.DisconnectResponse
	1,  // 9: transcoding.RegisterRequest.encoding_profiles:type_name -> transcoding.EncodingProfile
	1,  // 10: transcoding.NodeInfo.encoding_profiles:type_name -> transcoding.EncodingProfile
	17, // 11: transcoding.NodeInfo.last_seen:type_name -> google.protobuf.Timestamp
	13, // 12: transcoding.GetAllNodesResponse.nodes:type_name -> transcoding.NodeInfo
	2,  // 13: transcoding.VideoTranscoding.Stream:input_type -> transcoding.NodeMessage
	12, // 14: transcoding.VideoTranscoding.GetAllNodes:input_type -> transcoding.GetAllNodesRequest
	15, // 15: transcoding.VideoTranscoding.EnqueueJob:input_type -> transcoding.EnqueueJobRequest
	3,  // 16: transcoding.VideoTranscoding.Stream:output_type -> transcoding.OrchestratorMessage
	14, // 17: transcoding.VideoTranscoding.GetAllNodes:output_type -> transcoding.GetAllNodesResponse
	16, // 18: transcoding.VideoTranscoding.EnqueueJob:output_type -> transcoding.EnqueueJobResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_grpc_transcoding_transcoding_proto_init() }
func file_internal_grpc_transcoding_transcoding_proto_init() {
	if File_internal_grpc_transcoding_transcoding_proto != nil {
		return
	}
	file_internal_grpc_transcoding_transcoding_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_RegisterRequest)(nil),
		(*NodeMessage_ResourceUsageRequest)(nil),
		(*NodeMessage_DisconnectRequest)(nil),
	}
	file_internal_grpc_transcoding_transcoding_proto_msgTypes[3].OneofWrappers = []any{
		(*OrchestratorMessage_RegisterResponse)(nil),
		(*OrchestratorMessage_JobAssignmentRequest)(nil),
		(*OrchestratorMessage_DisconnectResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_transcoding_transcoding_proto_rawDesc), len(file_internal_grpc_transcoding_transcoding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_transcoding_transcoding_proto_goTypes,
		DependencyIndexes: file_internal_grpc_transcoding_transcoding_proto_depIdxs,
		MessageInfos:      file_internal_grpc_transcoding_transcoding_proto_msgTypes,
	}.Build()
	File_internal_grpc_transcoding_transcoding_proto = out.File
	file_internal_grpc_transcoding_transcoding_proto_goTypes = nil
	file_internal_grpc_transcoding_transcoding_proto_depIdxs = nil
}
