// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: internal/transcoding/transcoding.proto

package transcoding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_BUSY        NodeStatus = 2
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_BUSY",
		3: "NODE_STATUS_OFFLINE",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_BUSY":        2,
		"NODE_STATUS_OFFLINE":     3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transcoding_transcoding_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_transcoding_transcoding_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{0}
}

type MessageBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Unique identifier for request/response correlation
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBase) Reset() {
	*x = MessageBase{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBase) ProtoMessage() {}

func (x *MessageBase) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBase.ProtoReflect.Descriptor instead.
func (*MessageBase) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBase) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageBase) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Messages sent FROM nodes TO orchestrator
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *MessageBase           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_RegisterRequest
	//	*NodeMessage_ResourceUsageRequest
	//	*NodeMessage_JobAssignmentResponse
	//	*NodeMessage_DisconnectRequest
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMessage) GetBase() *MessageBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetResourceUsageRequest() *ResourceUsageRequest {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ResourceUsageRequest); ok {
			return x.ResourceUsageRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetJobAssignmentResponse() *JobAssignmentResponse {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_JobAssignmentResponse); ok {
			return x.JobAssignmentResponse
		}
	}
	return nil
}

func (x *NodeMessage) GetDisconnectRequest() *DisconnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_DisconnectRequest); ok {
			return x.DisconnectRequest
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_RegisterRequest struct {
	// Node registration
	RegisterRequest *RegisterRequest `protobuf:"bytes,2,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type NodeMessage_ResourceUsageRequest struct {
	// Resource usage monitoring
	ResourceUsageRequest *ResourceUsageRequest `protobuf:"bytes,3,opt,name=resource_usage_request,json=resourceUsageRequest,proto3,oneof"`
}

type NodeMessage_JobAssignmentResponse struct {
	// Job assignment response
	JobAssignmentResponse *JobAssignmentResponse `protobuf:"bytes,4,opt,name=job_assignment_response,json=jobAssignmentResponse,proto3,oneof"`
}

type NodeMessage_DisconnectRequest struct {
	// Node disconnection
	DisconnectRequest *DisconnectRequest `protobuf:"bytes,5,opt,name=disconnect_request,json=disconnectRequest,proto3,oneof"`
}

func (*NodeMessage_RegisterRequest) isNodeMessage_Payload() {}

func (*NodeMessage_ResourceUsageRequest) isNodeMessage_Payload() {}

func (*NodeMessage_JobAssignmentResponse) isNodeMessage_Payload() {}

func (*NodeMessage_DisconnectRequest) isNodeMessage_Payload() {}

// Messages sent FROM orchestrator TO nodes
type OrchestratorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *MessageBase           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OrchestratorMessage_RegisterResponse
	//	*OrchestratorMessage_ResourceUsageResponse
	//	*OrchestratorMessage_JobAssignmentRequest
	//	*OrchestratorMessage_DisconnectResponse
	Payload       isOrchestratorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{2}
}

func (x *OrchestratorMessage) GetBase() *MessageBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrchestratorMessage) GetPayload() isOrchestratorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OrchestratorMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetResourceUsageResponse() *ResourceUsageResponse {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_ResourceUsageResponse); ok {
			return x.ResourceUsageResponse
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetJobAssignmentRequest() *JobAssignmentRequest {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_JobAssignmentRequest); ok {
			return x.JobAssignmentRequest
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetDisconnectResponse() *DisconnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_DisconnectResponse); ok {
			return x.DisconnectResponse
		}
	}
	return nil
}

type isOrchestratorMessage_Payload interface {
	isOrchestratorMessage_Payload()
}

type OrchestratorMessage_RegisterResponse struct {
	// Node registration response
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type OrchestratorMessage_ResourceUsageResponse struct {
	// Resource usage acknowledgment
	ResourceUsageResponse *ResourceUsageResponse `protobuf:"bytes,3,opt,name=resource_usage_response,json=resourceUsageResponse,proto3,oneof"`
}

type OrchestratorMessage_JobAssignmentRequest struct {
	// Job assignment from orchestrator to node
	JobAssignmentRequest *JobAssignmentRequest `protobuf:"bytes,4,opt,name=job_assignment_request,json=jobAssignmentRequest,proto3,oneof"`
}

type OrchestratorMessage_DisconnectResponse struct {
	// Disconnect acknowledgment
	DisconnectResponse *DisconnectResponse `protobuf:"bytes,7,opt,name=disconnect_response,json=disconnectResponse,proto3,oneof"`
}

func (*OrchestratorMessage_RegisterResponse) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_ResourceUsageResponse) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_JobAssignmentRequest) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_DisconnectResponse) isOrchestratorMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Codecs        []string               `protobuf:"bytes,2,rep,name=codecs,proto3" json:"codecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResourceUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,4,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageRequest) Reset() {
	*x = ResourceUsageRequest{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageRequest) ProtoMessage() {}

func (x *ResourceUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageRequest.ProtoReflect.Descriptor instead.
func (*ResourceUsageRequest) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceUsageRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceUsageRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsageRequest) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ResourceUsageRequest) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

type ResourceUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageResponse) Reset() {
	*x = ResourceUsageResponse{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageResponse) ProtoMessage() {}

func (x *ResourceUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageResponse.ProtoReflect.Descriptor instead.
func (*ResourceUsageResponse) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResourceUsageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	InputPath     string                 `protobuf:"bytes,2,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	Crf           string                 `protobuf:"bytes,4,opt,name=crf,proto3" json:"crf,omitempty"`
	Preset        string                 `protobuf:"bytes,5,opt,name=preset,proto3" json:"preset,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,6,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,7,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignmentRequest) Reset() {
	*x = JobAssignmentRequest{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignmentRequest) ProtoMessage() {}

func (x *JobAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignmentRequest.ProtoReflect.Descriptor instead.
func (*JobAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{7}
}

func (x *JobAssignmentRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignmentRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *JobAssignmentRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *JobAssignmentRequest) GetCrf() string {
	if x != nil {
		return x.Crf
	}
	return ""
}

func (x *JobAssignmentRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *JobAssignmentRequest) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *JobAssignmentRequest) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

type JobAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignmentResponse) Reset() {
	*x = JobAssignmentResponse{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignmentResponse) ProtoMessage() {}

func (x *JobAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignmentResponse.ProtoReflect.Descriptor instead.
func (*JobAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{8}
}

func (x *JobAssignmentResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignmentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JobAssignmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{9}
}

func (x *DisconnectRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{10}
}

func (x *DisconnectResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type EncodingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputPath     string                 `protobuf:"bytes,1,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	Crf           string                 `protobuf:"bytes,3,opt,name=crf,proto3" json:"crf,omitempty"`
	Preset        string                 `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,5,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,6,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodingRequest) Reset() {
	*x = EncodingRequest{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodingRequest) ProtoMessage() {}

func (x *EncodingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodingRequest.ProtoReflect.Descriptor instead.
func (*EncodingRequest) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{11}
}

func (x *EncodingRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *EncodingRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *EncodingRequest) GetCrf() string {
	if x != nil {
		return x.Crf
	}
	return ""
}

func (x *EncodingRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *EncodingRequest) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *EncodingRequest) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

type EncodingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodingResponse) Reset() {
	*x = EncodingResponse{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodingResponse) ProtoMessage() {}

func (x *EncodingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodingResponse.ProtoReflect.Descriptor instead.
func (*EncodingResponse) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{12}
}

func (x *EncodingResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EncodingResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EncodingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{13}
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{14}
}

func (x *GetNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Codecs            []string               `protobuf:"bytes,3,rep,name=codecs,proto3" json:"codecs,omitempty"`
	LastResourceUsage *ResourceUsageRequest  `protobuf:"bytes,4,opt,name=last_resource_usage,json=lastResourceUsage,proto3" json:"last_resource_usage,omitempty"`
	RegisteredAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Status            NodeStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=transcoding.NodeStatus" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transcoding_transcoding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_transcoding_transcoding_proto_rawDescGZIP(), []int{15}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *NodeInfo) GetLastResourceUsage() *ResourceUsageRequest {
	if x != nil {
		return x.LastResourceUsage
	}
	return nil
}

func (x *NodeInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

var File_internal_transcoding_transcoding_proto protoreflect.FileDescriptor

const file_internal_transcoding_transcoding_proto_rawDesc = "" +
	"\n" +
	"&internal/transcoding/transcoding.proto\x12\vtranscoding\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\vMessageBase\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9b\x03\n" +
	"\vNodeMessage\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.transcoding.MessageBaseR\x04base\x12I\n" +
	"\x10register_request\x18\x02 \x01(\v2\x1c.transcoding.RegisterRequestH\x00R\x0fregisterRequest\x12Y\n" +
	"\x16resource_usage_request\x18\x03 \x01(\v2!.transcoding.ResourceUsageRequestH\x00R\x14resourceUsageRequest\x12\\\n" +
	"\x17job_assignment_response\x18\x04 \x01(\v2\".transcoding.JobAssignmentResponseH\x00R\x15jobAssignmentResponse\x12O\n" +
	"\x12disconnect_request\x18\x05 \x01(\v2\x1e.transcoding.DisconnectRequestH\x00R\x11disconnectRequestB\t\n" +
	"\apayload\"\xa9\x03\n" +
	"\x13OrchestratorMessage\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.transcoding.MessageBaseR\x04base\x12L\n" +
	"\x11register_response\x18\x02 \x01(\v2\x1d.transcoding.RegisterResponseH\x00R\x10registerResponse\x12\\\n" +
	"\x17resource_usage_response\x18\x03 \x01(\v2\".transcoding.ResourceUsageResponseH\x00R\x15resourceUsageResponse\x12Y\n" +
	"\x16job_assignment_request\x18\x04 \x01(\v2!.transcoding.JobAssignmentRequestH\x00R\x14jobAssignmentRequest\x12R\n" +
	"\x13disconnect_response\x18\a \x01(\v2\x1f.transcoding.DisconnectResponseH\x00R\x12disconnectResponseB\t\n" +
	"\apayload\"=\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06codecs\x18\x02 \x03(\tR\x06codecs\"_\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9a\x01\n" +
	"\x14ResourceUsageRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x04 \x01(\x01R\vdiskPercent\"K\n" +
	"\x15ResourceUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd9\x01\n" +
	"\x14JobAssignmentRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"input_path\x18\x02 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\x12\x10\n" +
	"\x03crf\x18\x04 \x01(\tR\x03crf\x12\x16\n" +
	"\x06preset\x18\x05 \x01(\tR\x06preset\x12\x1f\n" +
	"\vaudio_codec\x18\x06 \x01(\tR\n" +
	"audioCodec\x12\x1f\n" +
	"\vvideo_codec\x18\a \x01(\tR\n" +
	"videoCodec\"d\n" +
	"\x15JobAssignmentResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"D\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x12DisconnectResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xbd\x01\n" +
	"\x0fEncodingRequest\x12\x1d\n" +
	"\n" +
	"input_path\x18\x01 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x10\n" +
	"\x03crf\x18\x03 \x01(\tR\x03crf\x12\x16\n" +
	"\x06preset\x18\x04 \x01(\tR\x06preset\x12\x1f\n" +
	"\vaudio_codec\x18\x05 \x01(\tR\n" +
	"audioCodec\x12\x1f\n" +
	"\vvideo_codec\x18\x06 \x01(\tR\n" +
	"videoCodec\"_\n" +
	"\x10EncodingResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetNodesRequest\"?\n" +
	"\x10GetNodesResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.transcoding.NodeInfoR\x05nodes\"\x8b\x02\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06codecs\x18\x03 \x03(\tR\x06codecs\x12Q\n" +
	"\x13last_resource_usage\x18\x04 \x01(\v2!.transcoding.ResourceUsageRequestR\x11lastResourceUsage\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.transcoding.NodeStatusR\x06status*p\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x02\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x032\xfe\x01\n" +
	"\x10VideoTranscoding\x12H\n" +
	"\x06Stream\x12\x18.transcoding.NodeMessage\x1a .transcoding.OrchestratorMessage(\x010\x01\x12P\n" +
	"\x11GetAvailableNodes\x12\x1c.transcoding.GetNodesRequest\x1a\x1d.transcoding.GetNodesResponse\x12N\n" +
	"\x0fRequestEncoding\x12\x1c.transcoding.EncodingRequest\x1a\x1d.transcoding.EncodingResponseB/Z-github.com/svaan1/go-tcc/internal/transcodingb\x06proto3"

var (
	file_internal_transcoding_transcoding_proto_rawDescOnce sync.Once
	file_internal_transcoding_transcoding_proto_rawDescData []byte
)

func file_internal_transcoding_transcoding_proto_rawDescGZIP() []byte {
	file_internal_transcoding_transcoding_proto_rawDescOnce.Do(func() {
		file_internal_transcoding_transcoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transcoding_transcoding_proto_rawDesc), len(file_internal_transcoding_transcoding_proto_rawDesc)))
	})
	return file_internal_transcoding_transcoding_proto_rawDescData
}

var file_internal_transcoding_transcoding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_transcoding_transcoding_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_transcoding_transcoding_proto_goTypes = []any{
	(NodeStatus)(0),               // 0: transcoding.NodeStatus
	(*MessageBase)(nil),           // 1: transcoding.MessageBase
	(*NodeMessage)(nil),           // 2: transcoding.NodeMessage
	(*OrchestratorMessage)(nil),   // 3: transcoding.OrchestratorMessage
	(*RegisterRequest)(nil),       // 4: transcoding.RegisterRequest
	(*RegisterResponse)(nil),      // 5: transcoding.RegisterResponse
	(*ResourceUsageRequest)(nil),  // 6: transcoding.ResourceUsageRequest
	(*ResourceUsageResponse)(nil), // 7: transcoding.ResourceUsageResponse
	(*JobAssignmentRequest)(nil),  // 8: transcoding.JobAssignmentRequest
	(*JobAssignmentResponse)(nil), // 9: transcoding.JobAssignmentResponse
	(*DisconnectRequest)(nil),     // 10: transcoding.DisconnectRequest
	(*DisconnectResponse)(nil),    // 11: transcoding.DisconnectResponse
	(*EncodingRequest)(nil),       // 12: transcoding.EncodingRequest
	(*EncodingResponse)(nil),      // 13: transcoding.EncodingResponse
	(*GetNodesRequest)(nil),       // 14: transcoding.GetNodesRequest
	(*GetNodesResponse)(nil),      // 15: transcoding.GetNodesResponse
	(*NodeInfo)(nil),              // 16: transcoding.NodeInfo
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_internal_transcoding_transcoding_proto_depIdxs = []int32{
	17, // 0: transcoding.MessageBase.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: transcoding.NodeMessage.base:type_name -> transcoding.MessageBase
	4,  // 2: transcoding.NodeMessage.register_request:type_name -> transcoding.RegisterRequest
	6,  // 3: transcoding.NodeMessage.resource_usage_request:type_name -> transcoding.ResourceUsageRequest
	9,  // 4: transcoding.NodeMessage.job_assignment_response:type_name -> transcoding.JobAssignmentResponse
	10, // 5: transcoding.NodeMessage.disconnect_request:type_name -> transcoding.DisconnectRequest
	1,  // 6: transcoding.OrchestratorMessage.base:type_name -> transcoding.MessageBase
	5,  // 7: transcoding.OrchestratorMessage.register_response:type_name -> transcoding.RegisterResponse
	7,  // 8: transcoding.OrchestratorMessage.resource_usage_response:type_name -> transcoding.ResourceUsageResponse
	8,  // 9: transcoding.OrchestratorMessage.job_assignment_request:type_name -> transcoding.JobAssignmentRequest
	11, // 10: transcoding.OrchestratorMessage.disconnect_response:type_name -> transcoding.DisconnectResponse
	16, // 11: transcoding.GetNodesResponse.nodes:type_name -> transcoding.NodeInfo
	6,  // 12: transcoding.NodeInfo.last_resource_usage:type_name -> transcoding.ResourceUsageRequest
	17, // 13: transcoding.NodeInfo.registered_at:type_name -> google.protobuf.Timestamp
	0,  // 14: transcoding.NodeInfo.status:type_name -> transcoding.NodeStatus
	2,  // 15: transcoding.VideoTranscoding.Stream:input_type -> transcoding.NodeMessage
	14, // 16: transcoding.VideoTranscoding.GetAvailableNodes:input_type -> transcoding.GetNodesRequest
	12, // 17: transcoding.VideoTranscoding.RequestEncoding:input_type -> transcoding.EncodingRequest
	3,  // 18: transcoding.VideoTranscoding.Stream:output_type -> transcoding.OrchestratorMessage
	15, // 19: transcoding.VideoTranscoding.GetAvailableNodes:output_type -> transcoding.GetNodesResponse
	13, // 20: transcoding.VideoTranscoding.RequestEncoding:output_type -> transcoding.EncodingResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_transcoding_transcoding_proto_init() }
func file_internal_transcoding_transcoding_proto_init() {
	if File_internal_transcoding_transcoding_proto != nil {
		return
	}
	file_internal_transcoding_transcoding_proto_msgTypes[1].OneofWrappers = []any{
		(*NodeMessage_RegisterRequest)(nil),
		(*NodeMessage_ResourceUsageRequest)(nil),
		(*NodeMessage_JobAssignmentResponse)(nil),
		(*NodeMessage_DisconnectRequest)(nil),
	}
	file_internal_transcoding_transcoding_proto_msgTypes[2].OneofWrappers = []any{
		(*OrchestratorMessage_RegisterResponse)(nil),
		(*OrchestratorMessage_ResourceUsageResponse)(nil),
		(*OrchestratorMessage_JobAssignmentRequest)(nil),
		(*OrchestratorMessage_DisconnectResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transcoding_transcoding_proto_rawDesc), len(file_internal_transcoding_transcoding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transcoding_transcoding_proto_goTypes,
		DependencyIndexes: file_internal_transcoding_transcoding_proto_depIdxs,
		EnumInfos:         file_internal_transcoding_transcoding_proto_enumTypes,
		MessageInfos:      file_internal_transcoding_transcoding_proto_msgTypes,
	}.Build()
	File_internal_transcoding_transcoding_proto = out.File
	file_internal_transcoding_transcoding_proto_goTypes = nil
	file_internal_transcoding_transcoding_proto_depIdxs = nil
}
